abstract class NectarState {}
class InitState extends NectarState{}
class ShowPasswordSuccess extends NectarState{}
class DataSuccess extends NectarState{}
class DataError extends NectarState{}
class PlusSuccess extends NectarState{}
class MinisSuccess extends NectarState{}
class OnSelectSuccess extends NectarState{}
class ShowSuccess extends NectarState{}
class ChangeSuccess extends NectarState{}